# Use root/example as user/password credentials


version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=to_do_db
      - POSTGRES_USER=naile
      - POSTGRES_PASSWORD=""
    ports: 
      - 5455:5455
  